# [Air](https://github.com/cosmtrek/air) TOML 格式的配置文件

# root 表示项目的根目录，"." 表示当前目录
root = "."
# tmp_dir 表示 air 用于存储临时文件的目录
tmp_dir = "tmp"

# [build] 部分包含了构建项目的配置
[build]
# cmd 表示构建项目的命令
cmd = "go build -o ./tmp/main main.go"
# bin 表示构建后的二进制文件的路径
bin = "./tmp/main"
# full_bin 表示完整的运行命令，包括二进制文件和参数
full_bin = "./tmp/main"

# [watch] 部分包含了监视文件变化的配置
[watch]
 # include_ext 表示需要监视的文件扩展名
include_ext = ["go", "tpl", "tmpl", "html"]
# exclude_dir 表示需要排除的目录
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
# exclude_file 表示需要排除的文件
exclude_file = [""]
# 忽略这些文件扩展名或目录
exclude_regex = ["_test\\.go"]
# 如果文件更改过于频繁，则没有必要在每次更改时都触发构建。可以设置触发构建的延迟时间
delay = 1000 # ms
# 发生构建错误时，停止运行旧的二进制文件。
stop_on_error = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[screen]
	# 在重新构建时不清除屏幕内容。
  clear_on_rebuild = false
	# 在重新构建时保持滚动位置不变。
  keep_scroll = true