services:
  redis_server:
    image: redis:7.0 # 使用官方镜像
    container_name: go-redis
    restart: on-failure # always
    volumes:
      - ./data/redis/data:/data # 数据卷，持久化Redis数据
      - ./data/redis/logs:/logs
    command:
      - redis-server
    ports:
      - '6379:6379'
    environment:
      TZ: Asia/Shanghai  # 解决容器 时区的问题
  mysql_server:
    image: mysql:8.0
    container_name: go-mysql
    restart: on-failure # always
    environment:
      MYSQL_DATABASE: gin_db
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_ROOT_HOST: '%' # 允许任意主机连接
      TZ: Asia/Shanghai # 解决容器 时区的问题
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql/data:/var/lib/mysql # 数据卷，持久化MySQL数据
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
  web:
    container_name: gin-server
    depends_on: # 依赖于redis和mysql，在启动本服务之前会先启动依赖的服务
      - mysql_server
      - redis_server
    ports:
      - '8080:8080'
    build: # 根据Dockerfile构建镜像
      context: ./
      dockerfile: Dockerfile
    restart: on-failure # always
    # volumes:
      # 这个共享卷是用来存放配置文件。
      # - ./config/:/app/config/
